import Link from "next/link";
import { notFound } from "next/navigation";
import { getProject } from "@/lib/pipeline";
import { getRecommendedLayout } from "@/lib/db";
import { renderPlanSvg } from "@/lib/svg";
import {
  formatIdr,
  round1,
  STYLE_LABEL,
  PRIORITY_LABEL,
  ORIENTATION_LABEL,
  BUDGET_VERDICT_LABEL,
} from "@/lib/format";
import { QUESTIONS_FOR_TUKANG } from "@/lib/content";
import type { Warning } from "@/lib/schemas";
import VisualPanel from "./VisualPanel";
import RevisionSection from "./RevisionSection";

export const runtime = "nodejs";

const SEVERITY_STYLE: Record<Warning["severity"], { box: string; tag: string; label: string }> = {
  warning: { box: "border-red-200 bg-red-50", tag: "bg-red-600", label: "PERINGATAN" },
  tradeoff: { box: "border-amber-200 bg-amber-50", tag: "bg-amber-600", label: "TRADEOFF" },
  info: { box: "border-sky-200 bg-sky-50", tag: "bg-sky-600", label: "INFO" },
};

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const bundle = getProject(id);
  if (!bundle) notFound();

  const { brief, feasibility, layouts } = bundle;
  const recommendedLayout = getRecommendedLayout(id);

  return (
    <main className="mx-auto max-w-3xl px-5 py-10">
      <div className="mb-6 flex items-center justify-between gap-4">
        <h1 className="text-2xl font-bold text-slate-900">Brief Pra-Desain</h1>
        <a
          href={`/api/projects/${id}/pdf`}
          target="_blank"
          rel="noopener noreferrer"
          className="shrink-0 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700"
        >
          Unduh PDF
        </a>
      </div>

      {/* Ringkasan */}
      <section className="mb-8 rounded-xl border border-slate-200 p-5">
        <h2 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Ringkasan</h2>
        <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
          <Row k="Profil" v={brief.clientProfile} />
          <Row k="Tanah" v={`${brief.land.widthM} × ${brief.land.depthM} m (${feasibility.lotAreaM2} m²)`} />
          {brief.land.orientation && <Row k="Orientasi" v={ORIENTATION_LABEL[brief.land.orientation]} />}
          <Row k="Budget" v={formatIdr(brief.budgetIdr)} />
          <Row k="Lantai" v={String(brief.floors)} />
          <Row k="Kamar tidur" v={String(brief.bedrooms)} />
          <Row k="Kamar mandi" v={String(brief.bathrooms)} />
          <Row k="Gaya" v={STYLE_LABEL[brief.style]} />
          {brief.priorities.length > 0 && (
            <Row k="Prioritas" v={brief.priorities.map((p) => PRIORITY_LABEL[p]).join(", ")} />
          )}
        </dl>
      </section>

      {/* Feasibility */}
      <section className="mb-8">
        <h2 className="mb-1 text-lg font-semibold text-slate-900">Cek Kelayakan & Budget</h2>
        <p className="mb-4 text-sm text-slate-600">
          Status budget: <strong>{BUDGET_VERDICT_LABEL[feasibility.budgetVerdict]}</strong>. Estimasi biaya{" "}
          {formatIdr(feasibility.estimatedCost.lowIdr)} – {formatIdr(feasibility.estimatedCost.highIdr)} untuk
          ± {feasibility.estimatedBuildAreaM2} m² bangunan.
        </p>
        <div className="space-y-3">
          {feasibility.warnings.map((w, i) => {
            const st = SEVERITY_STYLE[w.severity];
            return (
              <div key={i} className={`rounded-lg border p-3 ${st.box}`}>
                <span className={`mb-1 inline-block rounded px-1.5 py-0.5 text-[10px] font-bold text-white ${st.tag}`}>
                  {st.label}
                </span>
                <p className="text-sm font-semibold text-slate-900">{w.title}</p>
                <p className="mt-0.5 text-sm text-slate-700">{w.detail}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* Denah */}
      <section className="mb-8">
        <h2 className="mb-4 text-lg font-semibold text-slate-900">2 Alternatif Denah Konsep</h2>
        <div className="grid gap-6 sm:grid-cols-2">
          {layouts.map((layout) => (
            <div
              key={layout.id}
              className={`rounded-xl border p-4 ${layout.id === recommendedLayout ? "border-slate-900 ring-1 ring-slate-900" : "border-slate-200"}`}
            >
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-slate-900">Denah {layout.id}</h3>
                {layout.id === recommendedLayout && (
                  <span className="rounded bg-slate-900 px-1.5 py-0.5 text-[10px] font-bold text-white">
                    DIREKOMENDASIKAN
                  </span>
                )}
              </div>
              <p className="mb-3 text-xs text-slate-600">{layout.summary}</p>
              <div
                className="overflow-hidden rounded-lg bg-white"
                // Trusted: SVG string is generated by our own renderer.
                dangerouslySetInnerHTML={{ __html: renderPlanSvg(layout) }}
              />
              <p className="mt-2 text-[11px] text-slate-500">
                Footprint ± {round1(layout.footprint.widthM)} × {round1(layout.footprint.depthM)} m. Biru = area basah.
              </p>
              {layout.notes.map((n, i) => (
                <p key={i} className="mt-1 text-[11px] text-amber-700">{n}</p>
              ))}
            </div>
          ))}
        </div>
      </section>

      {/* Revisi (AI) */}
      <section className="mb-8">
        <h2 className="mb-1 text-lg font-semibold text-slate-900">Revisi dengan Bahasa Sehari-hari (AI)</h2>
        <p className="mb-4 text-sm text-slate-600">
          Sampaikan perubahan yang diminta klien dengan kalimat biasa. AI menerjemahkannya
          menjadi perubahan brief; denah dan kelayakan dihitung ulang otomatis. Setiap revisi
          tersimpan sebagai versi yang bisa dibandingkan.
        </p>
        <RevisionSection projectId={id} />
      </section>

      {/* Visual konsep (AI) */}
      <section className="mb-8">
        <h2 className="mb-1 text-lg font-semibold text-slate-900">Visual Konsep 3D (AI)</h2>
        <p className="mb-4 text-sm text-slate-600">
          Buat 3D aerial (sudut 3/4 helicopter), tampak depan/belakang/samping/atas, dan denah
          interior berperabot — semuanya dibangun dari denah & data ruang yang sudah dihitung.
          Generate per tampak sesuai kebutuhan, bisa dibuat ulang sampai cocok, lalu disertakan
          di PDF. Penyesuaian dari revisi (mis. “warna lebih cerah”) otomatis ikut.
        </p>
        <VisualPanel projectId={id} initialVisuals={bundle.visuals} />
      </section>

      {/* Pertanyaan */}
      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold text-slate-900">Pertanyaan untuk Tukang / Kontraktor</h2>
        <ol className="list-decimal space-y-1.5 pl-5 text-sm text-slate-700">
          {QUESTIONS_FOR_TUKANG.map((q, i) => (
            <li key={i}>{q}</li>
          ))}
        </ol>
      </section>

      <p className="mb-6 rounded-md bg-amber-50 px-3 py-2 text-xs leading-relaxed text-amber-800">
        Konsep awal, bukan gambar kerja (DED) atau gambar siap bangun. Ukuran indikatif. Wajib
        direview arsitek / insinyur sipil / kontraktor sebelum dibangun.
      </p>

      <Link href="/" className="text-sm font-medium text-slate-600 underline hover:text-slate-900">
        ← Buat brief baru
      </Link>
    </main>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex flex-col">
      <dt className="text-xs text-slate-500">{k}</dt>
      <dd className="font-medium text-slate-900">{v}</dd>
    </div>
  );
}
